import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Loader from '../components/Loader'

import styles from '../styles/Home.module.css'

// let loading = false;


export default function Home() {
  const [loading, setLoading] = useState(true);
  return (
    <div>
      <Head>
        <title>Imo UX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>

      <main>
        <div style={{ height: '100vh', width: '100%', textAlign: 'center' }}>
          <div className={styles.heroHeadings}>
            <h3 className={styles.subheading}>Meet a next generation</h3>
            <h1 className={styles.heading}>Product Designer</h1>
          </div>
          <iframe
            id="spline"
            src='https://my.spline.design/portfoliohero-42c2c4614b0b42afdeb45b1d42f83c1f/'
            width='100%'
            height='100%'
            frameBorder='0'
            onLoad={() => {
              setLoading(false)
              console.log('hero loaded')
            }}
          ></iframe>
        </div>
        <Loader show={loading} />
      </main>
    </div>
  );
}
