import Head from 'next/head'
import Image from 'next/image'
import Loader from '../components/Loader'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Imo UX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>

      <main>
        <div style={{ height: '100vh', width: '100%' }}>
          <iframe src='https://my.spline.design/portfoliohero-42c2c4614b0b42afdeb45b1d42f83c1f/' width='100%' height='100%'></iframe>
          <div style={{ position: 'absolute', bottom: '2px', right: '2px', width: '100px', height: '100px', backgroundColor: '#FFFFFF' }}></div>
        </div>
        <div>
          <Loader show />
        </div>
      </main>
    </div>
  );
}

